name: watersupply
channels:
  - conda-forge
dependencies:
  - catboost=1.2.2
  - cudatoolkit=11.2
  - geopandas=0.14.1
  - keras=2.13.1
  - lightgbm=4.1.0
  - loguru=0.7
  - netCDF4=1.6.5
  - numba=0.58
  - numpy=1.26.2
  - odc-stac=0.3.8
  - pandas=2.1.3
  - pip=23.3
  - planetary-computer=1.0.0
  - pydantic=1.10
  - pystac=1.9.0
  - pytest=7.4
  - python=3.10.13
  - pytorch=1.13.1=cuda112*
  - pytorch-lightning=2.1.1
  - rasterio=1.3.9
  - rioxarray=0.15.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - statsmodels=0.14.0
  - tensorflow=2.13.1=cuda112*
  - tqdm=4.66
  - xarray=2023.11.0
  - xgboost=2.0.2=cuda112*
  - pip:
      - quantile-forest==1.2.3
